apiVersion: apps/v1
kind: Deployment

metadata:
  name: authsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authsvc
  template:
    metadata:
      labels:
        app: authsvc
    spec:
      containers:
        - name: authsvc
          image: 'this888dockerkde/authsvc:1.0.0'
          env:
            - name: DSN
              value: 'host=host.minikube.internal port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5'
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: authsvc
spec:
  selector:
    app: authsvc
  ports:
    - protocol: TCP
      name: web-port
      port: 80
      targetPort: 80
