apiVersion: apps/v1
kind: Deployment

metadata:
  name: mailsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailsvc
  template:
    metadata:
      labels:
        app: mailsvc
    spec:
      containers:
        - name: mailsvc
          image: 'this888dockerkde/mailsvc:1.0.0'
          env:
            - name: MAIL_DOMAIN
              value: localhost
            - name: MAIL_HOST
              value: mailhog
            - name: MAIL_PORT
              value: '1025'
            - name: MAIL_ENCRYPTION
              value: none
            - name: MAIL_USERNAME
              value: ''
            - name: MAIL_PASSWORD
              value: ''
            - name: MAIL_FROM_NAME
              value: 'John Smith'
            - name: MAIL_FROM_ADDRESS
              value: 'john.smith@example.com'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mailsvc
spec:
  selector:
    app: mailsvc
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80
